language: php 

php:
  - 5.3
  - 5.4
  - 5.5

notifications:
  email: false

env:
  - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-q --show-diff"

before_script:
  - ./travis/compile.sh

script:
  - make install
  - TEST_PHP_EXECUTABLE=`which php` php run-tests.php -n -d extension=swoole.so --show-diff
